"""
This file defines formatter functions for formating/outputting math 
problems generated by problem generators.

A formatter is a function with the following signature:

  (file, int, MathProblem) -> None

That is, a formatter function takes 3 arguments:

  - A file object (such as sys.stdout, or a file on disk)
  - An index (starting at 1) that represents the number of the problem
  in a set of problems
  - A MathProblem object that represents the math problem to format/output

A formatter function is expected to write a representation of the MathProblem
passed to it to the file object passed to the function.
"""

import random

def multiple_choice(out, i, problem):
  """Oututs a problem as a multiple-choce question
  suitable for a printed test."""
  print(f"{i}. {problem.question}", file = out)
  answers = [
    problem.right_answer, 
    problem.wrong_answer_1, 
    problem.wrong_answer_2, 
    problem.wrong_answer_3
  ]
  random.shuffle(answers)

  for pos, letter in enumerate(("a", "b", "c", "d")):
    answer = answers[pos]
    print(f"    {letter}. {answer}", file = out)

  print("", file = out)